#   _ __   ___  ___  __ _ _ __   __ _
#  | '_ \ / _ \/ __|/ _` | '_ \ / _` |
#  | | | | (_) \__ \ (_| | | | | (_| |
#  |_| |_|\___/|___/\__,_|_| |_|\__,_|

include:
  - project: nosana-ci/tools/cicd/gitlab-ci
    file: docker-container.yml

variables:
  DOCKERFILE_DIR: ./auto-update/
  CONTAINER_PLATFORMS: linux/amd64
  REG_REPOSITORY: nosana/nosana-node
  GITHUB_REPO: nosana-node # enables the github-release job on vX.Y.Z tags

npm install:
  image: node:20.11.1
  stage: build
  script:
    - npm ci
  artifacts:
    untracked: true
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# npm prettier:
#   image: node:20.11.1
#   stage: test
#   dependencies:
#     - npm install
#   script:
#     - npm run prettier # todo: fix eslint
#   rules:
#     - if: $CI_MERGE_REQUEST_ID
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

npm test:
  image: node:20.11.1
  stage: test
  dependencies:
    - npm install
  script:
    - npm run ci:test
  coverage: '/All files[^|]*\|[^|]*\|[^|]*\|[^|]*\|[^\d]*([\d\.]+)/'
  artifacts:
    when: always
    paths:
      - test-report.xml
    reports:
      junit: test-report.xml
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

npm publish beta:
  image: node:20.11.1
  stage: deploy
  script:
    - sed -i "s/0.0.0/${CI_COMMIT_TAG:1}-rc/" package.json
    - npm ci
    - npm shrinkwrap
    - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
    - npm run publish:next
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG != "latest"

npm publish prod:
  image: node:20.11.1
  stage: deploy
  script:
    - sed -i "s/0.0.0/${CI_COMMIT_TAG:1}/" package.json
    - npm ci
    - npm shrinkwrap
    - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
    - npm run publish:public
  when: manual
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG != "latest"

github release:
  extends: .github-release
  stage: deploy
  needs:
    - job: npm publish prod
