services:
  nosana_node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nosana-node
    command: start --network devnet --docker /etc/run/docker.sock
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /nosana
          ignore:
            - node_modules/
            - docs/
            - auto-update/
            - dist/
        - action: rebuild
          path: package.json
    image: nosana_node:latest
    networks:
      - NOSANA_GATEWAY
    volumes:
      - ~/.nosana/:/root/.nosana/
      - /var/run/docker.sock:/etc/run/docker.sock

networks:
  NOSANA_GATEWAY:
    name: NOSANA_GATEWAY
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.101.0/24
          gateway: 192.168.101.1
